name: I go to Comicon, guns, and thrash metal shows

on:
  push:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  a2s:
    name: Build Always OK Server for ${{ matrix.dickname }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: "CGO_ENABLED=0"
            dickname: "amd64"
          - tag: "CGO_ENABLED=0 GOARCH=arm64"
            dickname: "arm64"

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set up Go
        uses: actions/setup-go@main
        with:
          go-version: "stable"

      - name: Build!
        shell: bash
        run: |
          ${{ matrix.tag }} go build -o rsop-${{ matrix.dickname }}

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: Always-200OK-Server
          files: rsop-${{ matrix.dickname }}
          body: |
            # An always 200-OK Server
            ## ? Why do this
            - If you not bought `Rustdesk-Server-Pro`, the `21114 port` will be **TimeOut Error**.
            - So this is a program to solve this problem, It just a Always OK WebServer by Golang and listening 21114 port.
            ## ⚖️ License
            GNU AGPL-v3-or-later.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send to mirror
        uses: moaeiou/moaeiou/actions/rsync@main
        with:
          local: rsop-${{ matrix.dickname }}
          remote: luci-app/rsop/a2s/
          key: ${{ secrets.SSH_KEY }}

  build:
    needs: a2s
    name: Build for ${{ matrix.patch_arch }}
    runs-on: ubuntu-latest
    env:
      project_name: luci-app-rsop
    strategy:
      fail-fast: false
      matrix:
        include:
          - rdks_tag: "amd64"
            rsoparch: "amd64"
            patch_arch: "x86_64"
            sdk_arch: "x86-64"
          - rdks_tag: "arm64v8"
            rsoparch: "arm64"
            patch_arch: "aarch64_generic"
            sdk_arch: "rockchip-armv8"
          - rdks_tag: "arm64v8"
            rsoparch: "arm64"
            patch_arch: "aarch64_cortex-a53"
            sdk_arch: "mediatek-filogic"

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          path: ${{ env.project_name }}

      - name: Prepare SDK
        id: sdk
        uses: moaeiou/moaeiou/actions/prepare-sdk@main
        with:
          sdk_arch: ${{ matrix.sdk_arch }}
      
      - name: Get version
        id: get_version
        shell: bash
        run: |
          mv ${{ env.project_name }} ${{ steps.sdk.outputs.sdk_dir }}/package/
          cd ${{ steps.sdk.outputs.sdk_dir }}/package/${{ env.project_name }}
          VERSION=$(grep -E "^PKG_VERSION[[:space:]]*:=" Makefile | sed -E 's/.*:=[[:space:]]*//' | tr -d '[:space:]')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Prepare before compile
        shell: bash
        run: |
          cd ${{ steps.sdk.outputs.sdk_dir }}/package/${{ env.project_name }}
          if [ "${{ matrix.patch_arch }}" != "x86_64" ]; then
            sed -i 's/x86_64/${{ matrix.patch_arch }}/g' ./Makefile
          fi
          cd root/etc/rustdesk/
          wget -O rsop https://github.com/morouter/luci-app-rsop/releases/download/Always-200OK-Server/rsop-${{ matrix.rsoparch }}
          wget -O rustdesk-server.zip https://github.com/rustdesk/rustdesk-server/releases/latest/download/rustdesk-server-linux-${{ matrix.rdks_tag }}.zip
          unzip ./rustdesk-server.zip
          mv ./${{ matrix.rdks_tag }}/hbbr ./
          mv ./${{ matrix.rdks_tag }}/hbbs ./
          mv ./${{ matrix.rdks_tag }}/rustdesk-utils ./
          rm -rf ./${{ matrix.rdks_tag }} ./rustdesk-server.zip DONOTREMOVE ../../go.mod ../../main.go
          chmod +x ./hbbr ./hbbs ./rustdesk-utils ./rsop

      - name: Build!
        shell: bash
        run: |
          cd ${{ steps.sdk.outputs.sdk_dir }}
          make package/${{ env.project_name }}/compile V=s -j$(nproc)

      - name: Rename compilation files
        shell: bash
        run: |
          mv ${{ steps.sdk.outputs.sdk_dir }}/bin/packages/*/base/luci-app-*.apk ./luci-app-rsop-${{ matrix.patch_arch }}.apk
          mv ${{ steps.sdk.outputs.sdk_dir }}/bin/packages/*/base/luci-i18n-rsop-zh-cn-*.apk ./luci-i18n-rsop-zh-cn.apk
          mv ${{ steps.sdk.outputs.sdk_dir }}/bin/packages/*/base/luci-i18n-rsop-zh-tw-*.apk ./luci-i18n-rsop-zh-tw.apk
          ln -s ./luci-app-rsop-${{ matrix.patch_arch }}.apk ./luci-app-rsop-${{ steps.get_version.outputs.version }}-${{ matrix.patch_arch }}.apk

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: V${{ steps.get_version.outputs.version }}
          files: |
            luci-i18n-rsop-*.apk
            luci-app-rsop-${{ steps.get_version.outputs.version }}-${{ matrix.patch_arch }}.apk
          body: |
            # 📝 Release Notes
            - Fixes and improvements
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send to mirror
        uses: moaeiou/moaeiou/actions/rsync@main
        with:
          local: luci-i18n-rsop-*.apk luci-app-rsop-${{ matrix.patch_arch }}.apk
          remote: luci-app/rsop/
          key: ${{ secrets.SSH_KEY }}
          extra: --exclude='a2s/'
